Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spring2024_Books.Data;
using Spring2024_Books.Models;
using Spring2024_Books.Models.ViewModels;

namespace Spring2024_Books.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    //[Area("Customer")]
    //[Authorize(Roles = "Customer")]
    public class OrderController : Controller
    {
        private BooksDBContext _dbContext;

        [BindProperty]
        public OrderVM orderVM { get; set; }

        public OrderController(BooksDBContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Order> listOfOrders = _dbContext.Orders.Include(o => o.ApplicationUser).ToList();

            return View(listOfOrders);
        }
        public IActionResult Details(int id)

        {
            Order order = _dbContext.Orders.Find(id);

            IEnumerable<OrderDetail> orderDetails = _dbContext.OrderDetails.Where(o => o.OrderId == id).Include(od => od.Book);

            OrderVM orderVM = new OrderVM

            {
                Order = order,
                OrderDetails = orderDetails

            };
            return View(orderVM);

        }
        [HttpPost]
        public IActionResult UpdateOrderInformation()
        {
            Order orderFromDB = _dbContext.Orders.Find(orderVM.Order.OrderId);

            orderFromDB.CustomerName = orderVM.Order.CustomerName;
            orderFromDB.StreetAddress = orderVM.Order.StreetAddress;
            orderFromDB.City = orderVM.Order.City;
            orderFromDB.State = orderVM.Order.State;
            orderFromDB.PostalCode = orderVM.Order.PostalCode;
            orderFromDB.Phone = orderVM.Order.Phone;

            // if (!string.IsNullOrEmpty(orderVM.Order.ShippingDate.ToString()))
            orderFromDB.ShippingDate = orderVM.Order.ShippingDate;

            //  if (!string.IsNullOrEmpty(orderVM.Order.TrackingNumber))
            orderFromDB.TrackingNumber = orderVM.Order.TrackingNumber;

            //  if (!string.IsNullOrEmpty(orderVM.Order.Carrier))
            orderFromDB.Carrier = orderVM.Order.Carrier;

            orderFromDB.OrderStatus = orderVM.Order.OrderStatus;

            _dbContext.Orders.Update(orderFromDB);
            _dbContext.SaveChanges();

            return RedirectToAction("Details", new { id = orderFromDB.OrderId });
        }

        public IActionResult ProcessOrder()
        {
            Order order = _dbContext.Orders.Find(orderVM.Order.OrderId);

            order.ShippingDate = DateOnly.FromDateTime(DateTime.Now).AddDays(7);

            order.OrderStatus = "Processing";

            order.Carrier = "USPS";

            _dbContext.Orders.Update(order);
            _dbContext.SaveChanges();
            return RedirectToAction("Details", new { id = order.OrderId });



        }

        public IActionResult CompleteOrder()

        {
            Order order = _dbContext.Orders.Find(orderVM.Order.OrderId);

            order.OrderStatus = "Order Complete";


            order.ShippingDate = DateOnly.FromDateTime(DateTime.Now);

            _dbContext.Orders.Update(order);

            _dbContext.SaveChanges();

            return RedirectToAction("Details", new { id = order.OrderId });

        }





    }
}

Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Spring2024_Books.Data;

namespace Spring2024_Books.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class UserController : Controller
    {
        private BooksDBContext _dbContext;

        private UserManager<IdentityUser> _userManager;

        public UserController(BooksDBContext dbContext, UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;

            _dbContext = dbContext;
        }

        public IActionResult Index()
        {

            List<ApplicationUser> userList = _dbContext.ApplicationUsers.ToList();

            var allRoles = _dbContext.Roles.ToList();
            var userRoles = _dbContext.UserRoles.ToList();

            foreach (var u in userList)
            {
                //find first user in the list, get me the role ID, i eventually want the role name
                var roleId = userRoles.Find(ur => ur.UserId == u.Id).RoleId;

                var roleName = allRoles.Find(r => r.Id == roleId).Name;

                u.RoleName = roleName;
            }


            return View(userList);
        }

        public IActionResult LockUnlock(string id)
        {

            var userFromDB = _dbContext.ApplicationUsers.Find(id);

            if (userFromDB.LockoutEnd != null && userFromDB.LockoutEnd > DateTime.Now)
            {
                userFromDB.LockoutEnd = DateTime.Now.AddYears(10);

            }
            else
            {
                userFromDB.LockoutEnd = DateTime.Now.AddYears(10);


            }
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]

        public IActionResult EditUserRole(string id)
        {
            var currentUserRole = _dbContext.UserRoles.FirstOrDefault(ur => ur.UserId == id);


            IEnumerable<SelectListItem> listOfRoles = _dbContext.Roles.ToList().Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id.ToString()
            });


            ViewBag.ListOfRoles = listOfRoles;

            ViewBag.UserInfo = _dbContext.ApplicationUsers.Find(id);

            return View(currentUserRole);




        }

        [HttpPost]
        public IActionResult EditUserRole(IdentityUserRole<string> updatedRole)
        {
            ApplicationUser applicationUser = _dbContext.ApplicationUsers.Find(updatedRole.UserId);

            string newRoleName = _dbContext.Roles.Find(updatedRole.RoleId).Name;

            string oldRoleId = _dbContext.UserRoles.FirstOrDefault(u => u.UserId == applicationUser.Id).RoleId;

            string oldRoleName = _dbContext.Roles.Find(oldRoleId).Name;

            _userManager.RemoveFromRoleAsync(applicationUser, oldRoleName).GetAwaiter().GetResult();

            _userManager.AddToRoleAsync(applicationUser, oldRoleName).GetAwaiter().GetResult();

            return RedirectToAction("Index");


        }



    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spring2024_Books</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Spring2024_Books.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Customer") || User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>

                            
                          
                        }

                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Book" asp-action="Index">Books</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Orders</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="User" asp-action="Index">Manage User</a>
                            </li>

                        }
                    </ul>

                    <partial name= "_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Spring2024_Books - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>